kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postgresql
  namespace: rag-llm-demo
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  volumeMode: Filesystem