
bases:
  - ../base


commonLabels:
  db-engine: mongodb
  environment: development

patchesJson6902:
  - target:
      group: mongodbcommunity.mongodb.com
      version: v1
      kind: MongoDBCommunity
      name: mongodb-instance
    patch: |-
      - op: replace
        path: spec/statefulSet/spec/template/spec/containers/0/resources
        value:
          requests:
            cpu: "1"
            memory: "1Gi"
          limits:
            cpu: "2"
            memory: "2Gi"