
bases:
  - ../../base

patches:
  - target:
      group: mongodbcommunity.mongodb.com
      version: v1
      kind: MongoDBCommunity
      name: mongodb-instance
    patch: |-
      - op: replace
        path: /spec/statefulSet/spec/template/spec/containers/0/resources
        value:
          requests:
            cpu: "1"
            memory: "1Gi"
          limits:
            cpu: "2"
            memory: "2Gi"
  - target:
      group: rbac.authorization.k8s.io
      version: v1
      kind: RoleBinding
      name: system:openshift:scc:anyuid
    patch: |-
      - op: replace
        path: /subjects/0/namespace
        value: mongodb-prod
      - op: replace
        path: /subjects/1/namespace
        value: mongodb-prod