kind: Secret
apiVersion: v1
metadata:
  name: {{ include "quiz-db-app.fullname" . }}-mongo-connection
  labels:
    {{- include "quiz-db-app.labels" . | nindent 4 }}
stringData:
  JDB_Engine: {{ .Values.db_connection.JDB_Engine }}
  MONGO_URI: {{ .Values.db_connection.MONGO_URI }}
