apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mongodb
  namespace: openshift-gitops
spec:
  project: default
  sources:
    - chart: community-operator
      repoURL: https://mongodb.github.io/helm-charts
      targetRevision: "*"
  destination:
    server: "https://kubernetes.default.svc"
    namespace: mongodb
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
