---
apiVersion: v1
kind: Secret
metadata:
  name: kfp-s3-credentials
  namespace: rag-llm-demo
stringData:          # ← texto plano, ArgoCD/k8s hace el base64 internamente
  AWS_ACCESS_KEY_ID: minioadmin
  AWS_SECRET_ACCESS_KEY: minioadmin